[package]
name = "battle_city"
version = "0.1.0"
authors = ["wolf1996 <ksgiv37@gmail.com>"]

[dependencies]
  ws = "*"
  serde_json = "1.0"
  serde = "1.0"
  serde_derive = "1.0"
  erased-serde = "0.3"